# Name: Tejas Bhat, Aayush Patel
# Email: tejasgbhat@gmail.com, aayushpatel108@ucla.edu
# ID: 705199445, 105111196
.SILENT:

default:
	gcc -o lab3a -lm -std=gnu99 -g -Wall -Wextra lab3a.c

dist:
	tar -czvf lab3a-105111196.tar.gz lab3a.c ext2_fs.h Makefile README

clean: 
	rm -f lab3a-105111196.tar.gz lab3a
